# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminGUI.ui'
#
# Created: Sun May 22 04:18:24 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.playBtn = QtGui.QPushButton(self.tab)
        self.playBtn.setObjectName(_fromUtf8("playBtn"))
        self.gridLayout.addWidget(self.playBtn, 1, 0, 1, 1)
        self.skipButton = QtGui.QPushButton(self.tab)
        self.skipButton.setObjectName(_fromUtf8("skipButton"))
        self.gridLayout.addWidget(self.skipButton, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 7, 1, 1)
        self.stopBtn = QtGui.QPushButton(self.tab)
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.gridLayout.addWidget(self.stopBtn, 1, 1, 1, 1)
        self.volumeSlider = QtGui.QSlider(self.tab)
        self.volumeSlider.setMinimumSize(QtCore.QSize(50, 0))
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.gridLayout.addWidget(self.volumeSlider, 1, 8, 1, 1)
        self.trackTime = QtGui.QLabel(self.tab)
        self.trackTime.setObjectName(_fromUtf8("trackTime"))
        self.gridLayout.addWidget(self.trackTime, 1, 5, 1, 1)
        self.graphicsView = QtGui.QGraphicsView(self.tab)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 9)
        self.trackSlide = QtGui.QSlider(self.tab)
        self.trackSlide.setMinimumSize(QtCore.QSize(300, 0))
        self.trackSlide.setOrientation(QtCore.Qt.Horizontal)
        self.trackSlide.setObjectName(_fromUtf8("trackSlide"))
        self.gridLayout.addWidget(self.trackSlide, 1, 3, 1, 2)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 6, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.restartServer = QtGui.QPushButton(self.groupBox_2)
        self.restartServer.setObjectName(_fromUtf8("restartServer"))
        self.gridLayout_5.addWidget(self.restartServer, 1, 0, 1, 1)
        self.viewLogs = QtGui.QPushButton(self.groupBox_2)
        self.viewLogs.setObjectName(_fromUtf8("viewLogs"))
        self.gridLayout_5.addWidget(self.viewLogs, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setMaximumSize(QtCore.QSize(370, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.removeUser = QtGui.QPushButton(self.groupBox)
        self.removeUser.setObjectName(_fromUtf8("removeUser"))
        self.gridLayout_4.addWidget(self.removeUser, 3, 1, 1, 1)
        self.userList = QtGui.QListWidget(self.groupBox)
        self.userList.setObjectName(_fromUtf8("userList"))
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.userList.addItem(item)
        self.gridLayout_4.addWidget(self.userList, 1, 0, 1, 3)
        self.banUser = QtGui.QPushButton(self.groupBox)
        self.banUser.setObjectName(_fromUtf8("banUser"))
        self.gridLayout_4.addWidget(self.banUser, 4, 1, 1, 1)
        self.userGo = QtGui.QPushButton(self.groupBox)
        self.userGo.setObjectName(_fromUtf8("userGo"))
        self.gridLayout_4.addWidget(self.userGo, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.userSearch = QtGui.QLineEdit(self.groupBox)
        self.userSearch.setObjectName(_fromUtf8("userSearch"))
        self.gridLayout_4.addWidget(self.userSearch, 0, 1, 1, 1)
        self.userMusic = QtGui.QPushButton(self.groupBox)
        self.userMusic.setObjectName(_fromUtf8("userMusic"))
        self.gridLayout_4.addWidget(self.userMusic, 5, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NukeBox 2000 Server", None))
        self.playBtn.setText(_translate("MainWindow", "Play", None))
        self.skipButton.setText(_translate("MainWindow", "Skip", None))
        self.label_2.setText(_translate("MainWindow", "Volume:", None))
        self.stopBtn.setText(_translate("MainWindow", "Stop", None))
        self.trackTime.setText(_translate("MainWindow", "2:36/3:28", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Application Control", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Server Admin", None))
        self.restartServer.setText(_translate("MainWindow", "Restart Server", None))
        self.viewLogs.setText(_translate("MainWindow", "View Logs", None))
        self.groupBox.setTitle(_translate("MainWindow", "User Administration", None))
        self.removeUser.setText(_translate("MainWindow", "Remove User", None))
        __sortingEnabled = self.userList.isSortingEnabled()
        self.userList.setSortingEnabled(False)
        item = self.userList.item(0)
        item.setText(_translate("MainWindow", "Conor", None))
        item = self.userList.item(1)
        item.setText(_translate("MainWindow", "Chris", None))
        item = self.userList.item(2)
        item.setText(_translate("MainWindow", "Roger", None))
        item = self.userList.item(3)
        item.setText(_translate("MainWindow", "Darren", None))
        item = self.userList.item(4)
        item.setText(_translate("MainWindow", "Paul", None))
        item = self.userList.item(5)
        item.setText(_translate("MainWindow", "Andrezj", None))
        item = self.userList.item(6)
        item.setText(_translate("MainWindow", "David", None))
        item = self.userList.item(7)
        item.setText(_translate("MainWindow", "Brian", None))
        item = self.userList.item(8)
        item.setText(_translate("MainWindow", "David", None))
        item = self.userList.item(9)
        item.setText(_translate("MainWindow", "Diarmuid", None))
        item = self.userList.item(10)
        item.setText(_translate("MainWindow", "Cormac", None))
        self.userList.setSortingEnabled(__sortingEnabled)
        self.banUser.setText(_translate("MainWindow", "Ban User", None))
        self.userGo.setText(_translate("MainWindow", "Go", None))
        self.label.setText(_translate("MainWindow", "Search Users:", None))
        self.userMusic.setText(_translate("MainWindow", "Remove User Music", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Administration", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

